### Path does not exist
GET http://localhost:3030/sdfert

###
GET http://localhost:3030/

###
GET http://localhost:3030/about

###
GET http://localhost:3030/about/

###
GET http://localhost:3030/about/12

###
GET http://localhost:3030/user/12/photo/33

###
GET http://localhost:3030/toronto/one/ca12n

###
GET http://localhost:3030/chain

###
GET http://localhost:3030/chainhalt

###
PATCH http://localhost:3030/comment

###
PATCH http://localhost:3030/comment/how-to

###
PATCH http://localhost:3030/comment/how
Content-Type: application/json

{
  "message": "hello world"
}

###
POST http://localhost:3030/comment
Content-Type: text/html

<p>hello world</p>

###
POST http://localhost:3030/comment/how-to
Content-Type: text/html

<p>hello world</p>

###
POST http://localhost:3030/comment/how
Content-Type: application/json

{
  "message": "hello world"
}

###
PUT http://localhost:3030/comment
Content-Type: text/html

<p>hello world</p>

###
PUT http://localhost:3030/comment/how-to
Content-Type: text/html

<p>hello world</p>

###
PUT http://localhost:3030/comment/how
Content-Type: text/html

<p>hello world</p>

###
DELETE http://localhost:3030/comment

###
DELETE http://localhost:3030/comment/how-to

###
DELETE http://localhost:3030/comment/how

###
GET http://localhost:3030/middleware

###
GET http://localhost:3030/middleware2

###
GET http://localhost:3030/about?s=45bnj34

###
GET http://localhost:3030/about/?we=394845hjh

###
GET http://localhost:3030?q=dfjriour

###
GET http://localhost:3030/query-check?q=dfjriour

###
GET http://localhost:3030/query-check/?aa=12&bb&c=33

###
GET http://localhost:3030/query-check/?12=aa

###
GET http://localhost:3030/regex/12345/dept

###
GET http://localhost:3030/regex/toronto

###
GET http://localhost:3030/regex/tooronto

###
GET http://localhost:3030/regex/tronto

###
GET http://localhost:3030/regex/5toronto

### Test static route before named route
GET http://localhost:3030/foo/bar

### Test static route before named route
GET http://localhost:3030/foo/boo

### Test static route before named route
GET http://localhost:3030/foo/boo/bar1

### Test static route before named route
GET http://localhost:3030/foo/boo/bar2

### Test static route before named route
GET http://localhost:3030/foo/boo/bar2/bar

### Test static route before named route
GET http://localhost:3030/foo/boo/bar2/car

### Test static route before named route
GET http://localhost:3030/foo/moo/bar2/bar

### Test for unsupported method
HEAD http://localhost:3030/mox

### Test path does not exist
GET http://localhost:3030/regex/123/dept

###
GET http://localhost:3030/headers
Cookie: sessionId=abc123
Cookie: user=yadav12

###
GET http://localhost:3030/
###
GET http://localhost:3030/home
###
GET http://localhost:3030/api/v1/about
###
GET http://localhost:3030/api/v1/about/me


###
GET http://localhost:3030/one
