###
GET http://localhost:3100/sdfert

###
GET http://localhost:3100/

###
GET http://localhost:3100/about

###
GET http://localhost:3100/about/

###
GET http://localhost:3100/about/12

###
GET http://localhost:3100/user/12/photo/33

###
GET http://localhost:3100/toronto/one/ca12n

###
GET http://localhost:3100/chain

###
GET http://localhost:3100/chainhalt

###
PATCH http://localhost:3100/comment

###
PATCH http://localhost:3100/comment/how-to

###
PATCH http://localhost:3100/comment/how

{
  "message": "hello world"
}

###
POST http://localhost:3100/comment
Content-Type: text/html

<p>hello world</p>

###
POST http://localhost:3100/comment/how-to
Content-Type: text/html

<p>hello world</p>

###
POST http://localhost:3100/comment/how
Content-Type: application/json

{
  "message": "hello world"
}

###
PUT http://localhost:3100/comment
Content-Type: text/html

<p>hello world</p>

###
PUT http://localhost:3100/comment/how-to
Content-Type: text/html

<p>hello world</p>

###
PUT http://localhost:3100/comment/how
Content-Type: text/html

<p>hello world</p>

###
DELETE http://localhost:3100/comment

###
DELETE http://localhost:3100/comment/how-to

###
DELETE http://localhost:3100/comment/how

###
GET http://localhost:3100/middleware

###
GET http://localhost:3100/about?s=45bnj34

###
GET http://localhost:3100/about/?we=394845hjh

###
GET http://localhost:3100?q=dfjriour

###
GET http://localhost:3100/query-check?q=dfjriour

###
GET http://localhost:3100/query-check/?aa=12&&bb&&c=33

###
GET http://localhost:3100/query-check/?12=aa

###
GET http://localhost:3100/regex/12345/dept

###
GET http://localhost:3100/regex/toronto

###
GET http://localhost:3100/regex/tooronto

###
GET http://localhost:3100/regex/tronto

###
GET http://localhost:3100/regex/5toronto

### Test static route before named route
GET http://localhost:3100/foo/bar

### Test static route before named route
GET http://localhost:3100/foo/boo

### Test static route before named route
GET http://localhost:3100/foo/boo/bar1

### Test static route before named route
GET http://localhost:3100/foo/boo/bar2

### Test static route before named route
GET http://localhost:3100/foo/boo/bar2/bar

### Test static route before named route
GET http://localhost:3100/foo/boo/bar2/car

### Test static route before named route
GET http://localhost:3100/foo/moo/bar2/bar
